# Generated by Django 5.0.6 on 2024-07-02 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.alumno')),
            ],
        ),
        migrations.CreateModel(
            name='CursoMateria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CursoProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MateriaProfesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.materia')),
            ],
        ),
        migrations.DeleteModel(
            name='Entregable',
        ),
        migrations.DeleteModel(
            name='Estudiante',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='profesion',
        ),
        migrations.AddField(
            model_name='curso',
            name='turno',
            field=models.CharField(choices=[('mañana', 'Mañana'), ('tarde', 'Tarde'), ('vespertino', 'Vespertino')], default='Mañana', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='curso',
            name='division',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='curso',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profesor',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AddField(
            model_name='alumnocurso',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.curso'),
        ),
        migrations.AddField(
            model_name='curso',
            name='alumnos',
            field=models.ManyToManyField(through='repositorio.AlumnoCurso', to='repositorio.alumno'),
        ),
        migrations.AddField(
            model_name='alumnoprofesor',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.profesor'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='profesores',
            field=models.ManyToManyField(through='repositorio.AlumnoProfesor', to='repositorio.profesor'),
        ),
        migrations.AddField(
            model_name='cursomateria',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.curso'),
        ),
        migrations.AddField(
            model_name='cursoprofesor',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.curso'),
        ),
        migrations.AddField(
            model_name='cursoprofesor',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.profesor'),
        ),
        migrations.AddField(
            model_name='curso',
            name='profesores',
            field=models.ManyToManyField(through='repositorio.CursoProfesor', to='repositorio.profesor'),
        ),
        migrations.AddField(
            model_name='cursoprofesor',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.materia'),
        ),
        migrations.AddField(
            model_name='cursomateria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.materia'),
        ),
        migrations.AddField(
            model_name='alumnoprofesor',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.materia'),
        ),
        migrations.AddField(
            model_name='alumnomateria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.materia'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='materias',
            field=models.ManyToManyField(through='repositorio.AlumnoMateria', to='repositorio.materia'),
        ),
        migrations.AddField(
            model_name='curso',
            name='materias',
            field=models.ManyToManyField(through='repositorio.CursoMateria', to='repositorio.materia'),
        ),
        migrations.AddField(
            model_name='materiaprofesor',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repositorio.profesor'),
        ),
        migrations.AddField(
            model_name='profesor',
            name='materias',
            field=models.ManyToManyField(through='repositorio.MateriaProfesor', to='repositorio.materia'),
        ),
    ]
